INSERT INTO ospos_location (location_name) VALUES ('Bakri');
INSERT INTO ospos_location (location_name) VALUES ('Batu Pahat');
INSERT INTO ospos_location (location_name) VALUES ('Buloh Kasap');
INSERT INTO ospos_location (location_name) VALUES ('Chaah');
INSERT INTO ospos_location (location_name) VALUES ('Daerah Batu Pahat');
INSERT INTO ospos_location (location_name) VALUES ('Daerah Johor Baharu');
INSERT INTO ospos_location (location_name) VALUES ('Daerah Keluang');
INSERT INTO ospos_location (location_name) VALUES ('Daerah Kota Tinggi');
INSERT INTO ospos_location (location_name) VALUES ('Daerah Mersing');
INSERT INTO ospos_location (location_name) VALUES ('Daerah Muar');
INSERT INTO ospos_location (location_name) VALUES ('Daerah Pontian');
INSERT INTO ospos_location (location_name) VALUES ('Daerah Segamat');
INSERT INTO ospos_location (location_name) VALUES ('Johor Bahru');
INSERT INTO ospos_location (location_name) VALUES ('Kampung Pasir Gudang Baru');
INSERT INTO ospos_location (location_name) VALUES ('Kampung Simpang Renggam');
INSERT INTO ospos_location (location_name) VALUES ('Kelapa Sawit');
INSERT INTO ospos_location (location_name) VALUES ('Kluang');
INSERT INTO ospos_location (location_name) VALUES ('Kota Tinggi');
INSERT INTO ospos_location (location_name) VALUES ('Kulai');
INSERT INTO ospos_location (location_name) VALUES ('Labis');
INSERT INTO ospos_location (location_name) VALUES ('Mersing');
INSERT INTO ospos_location (location_name) VALUES ('Muar');
INSERT INTO ospos_location (location_name) VALUES ('Parit Raja');
INSERT INTO ospos_location (location_name) VALUES ('Pekan Nenas');
INSERT INTO ospos_location (location_name) VALUES ('Pontian Kechil');
INSERT INTO ospos_location (location_name) VALUES ('Segamat');
INSERT INTO ospos_location (location_name) VALUES ('Skudai');
INSERT INTO ospos_location (location_name) VALUES ('Taman Senai');
INSERT INTO ospos_location (location_name) VALUES ('Tangkak');
INSERT INTO ospos_location (location_name) VALUES ('Ulu Tiram');
INSERT INTO ospos_location (location_name) VALUES ('Yong Peng');
INSERT INTO ospos_location (location_name) VALUES ('Alor Setar');
INSERT INTO ospos_location (location_name) VALUES ('Ayer Hangat');
INSERT INTO ospos_location (location_name) VALUES ('Bedong');
INSERT INTO ospos_location (location_name) VALUES ('Gurun');
INSERT INTO ospos_location (location_name) VALUES ('Jitra');
INSERT INTO ospos_location (location_name) VALUES ('Kampung Kilim');
INSERT INTO ospos_location (location_name) VALUES ('Kampung Kok');
INSERT INTO ospos_location (location_name) VALUES ('Kuah');
INSERT INTO ospos_location (location_name) VALUES ('Kuala Kedah');
INSERT INTO ospos_location (location_name) VALUES ('Kuala Teriang');
INSERT INTO ospos_location (location_name) VALUES ('Kulim');
INSERT INTO ospos_location (location_name) VALUES ('Langkawi');
INSERT INTO ospos_location (location_name) VALUES ('Padang Mat Sirat');
INSERT INTO ospos_location (location_name) VALUES ('Sungai Petani');
INSERT INTO ospos_location (location_name) VALUES ('Gua Musang');
INSERT INTO ospos_location (location_name) VALUES ('Kampong Kadok');
INSERT INTO ospos_location (location_name) VALUES ('Kampong Pangkal Kalong');
INSERT INTO ospos_location (location_name) VALUES ('Kota Bharu');
INSERT INTO ospos_location (location_name) VALUES ('Pasir Mas');
INSERT INTO ospos_location (location_name) VALUES ('Peringat');
INSERT INTO ospos_location (location_name) VALUES ('Tumpat');
INSERT INTO ospos_location (location_name) VALUES ('Kuala Lumpur');
INSERT INTO ospos_location (location_name) VALUES ('Labuan');
INSERT INTO ospos_location (location_name) VALUES ('Alor Gajah');
INSERT INTO ospos_location (location_name) VALUES ('Batu Berendam');
INSERT INTO ospos_location (location_name) VALUES ('Bemban');
INSERT INTO ospos_location (location_name) VALUES ('Bukit Rambai');
INSERT INTO ospos_location (location_name) VALUES ('Kampong Masjid Tanah');
INSERT INTO ospos_location (location_name) VALUES ('Kampung Ayer Keroh');
INSERT INTO ospos_location (location_name) VALUES ('Kampung Ayer Molek');
INSERT INTO ospos_location (location_name) VALUES ('Kampung Bukit Baharu');
INSERT INTO ospos_location (location_name) VALUES ('Klebang Besar');
INSERT INTO ospos_location (location_name) VALUES ('Kuala Sungai Baru');
INSERT INTO ospos_location (location_name) VALUES ('Malacca');
INSERT INTO ospos_location (location_name) VALUES ('Pulau Sebang');
INSERT INTO ospos_location (location_name) VALUES ('Sungai Udang');
INSERT INTO ospos_location (location_name) VALUES ('Bahau');
INSERT INTO ospos_location (location_name) VALUES ('Kampung Baharu Nilai');
INSERT INTO ospos_location (location_name) VALUES ('Kuala Pilah');
INSERT INTO ospos_location (location_name) VALUES ('Port Dickson');
INSERT INTO ospos_location (location_name) VALUES ('Seremban');
INSERT INTO ospos_location (location_name) VALUES ('Tampin');
INSERT INTO ospos_location (location_name) VALUES ('Bentong Town');
INSERT INTO ospos_location (location_name) VALUES ('Jerantut');
INSERT INTO ospos_location (location_name) VALUES ('Kampung Bukit Tinggi Bentong');
INSERT INTO ospos_location (location_name) VALUES ('Kampung Tekek');
INSERT INTO ospos_location (location_name) VALUES ('Kuala Lipis');
INSERT INTO ospos_location (location_name) VALUES ('Kuantan');
INSERT INTO ospos_location (location_name) VALUES ('Mentekab');
INSERT INTO ospos_location (location_name) VALUES ('Pekan');
INSERT INTO ospos_location (location_name) VALUES ('Raub');
INSERT INTO ospos_location (location_name) VALUES ('Tanah Rata');
INSERT INTO ospos_location (location_name) VALUES ('Temerluh');
INSERT INTO ospos_location (location_name) VALUES ('Batu Feringgi');
INSERT INTO ospos_location (location_name) VALUES ('Bukit Mertajam');
INSERT INTO ospos_location (location_name) VALUES ('Butterworth');
INSERT INTO ospos_location (location_name) VALUES ('George Town');
INSERT INTO ospos_location (location_name) VALUES ('Juru');
INSERT INTO ospos_location (location_name) VALUES ('Kampung Batu Feringgi');
INSERT INTO ospos_location (location_name) VALUES ('Kampung Sungai Ara');
INSERT INTO ospos_location (location_name) VALUES ('Kepala Batas');
INSERT INTO ospos_location (location_name) VALUES ('Nibong Tebal');
INSERT INTO ospos_location (location_name) VALUES ('Perai');
INSERT INTO ospos_location (location_name) VALUES ('Permatang Kuching');
INSERT INTO ospos_location (location_name) VALUES ('Seberang Perai');
INSERT INTO ospos_location (location_name) VALUES ('Tanjung Tokong');
INSERT INTO ospos_location (location_name) VALUES ('Tasek Glugor');
INSERT INTO ospos_location (location_name) VALUES ('Telaga Batu');
INSERT INTO ospos_location (location_name) VALUES ('Bagan Serai');
INSERT INTO ospos_location (location_name) VALUES ('Batu Gajah');
INSERT INTO ospos_location (location_name) VALUES ('Bidur');
INSERT INTO ospos_location (location_name) VALUES ('Ipoh');
INSERT INTO ospos_location (location_name) VALUES ('Kampar');
INSERT INTO ospos_location (location_name) VALUES ('Kampong Dungun');
INSERT INTO ospos_location (location_name) VALUES ('Kuala Kangsar');
INSERT INTO ospos_location (location_name) VALUES ('Lumut');
INSERT INTO ospos_location (location_name) VALUES ('Pantai Remis');
INSERT INTO ospos_location (location_name) VALUES ('Parit Buntar');
INSERT INTO ospos_location (location_name) VALUES ('Simpang Empat');
INSERT INTO ospos_location (location_name) VALUES ('Taiping');
INSERT INTO ospos_location (location_name) VALUES ('Tapah Road');
INSERT INTO ospos_location (location_name) VALUES ('Teluk Intan');
INSERT INTO ospos_location (location_name) VALUES ('Kangar');
INSERT INTO ospos_location (location_name) VALUES ('Kuala Perlis');
INSERT INTO ospos_location (location_name) VALUES ('Pantai Cenang');
INSERT INTO ospos_location (location_name) VALUES ('Putrajaya');
INSERT INTO ospos_location (location_name) VALUES ('Bandar Labuan');
INSERT INTO ospos_location (location_name) VALUES ('Beaufort');
INSERT INTO ospos_location (location_name) VALUES ('Donggongon');
INSERT INTO ospos_location (location_name) VALUES ('Keningau');
INSERT INTO ospos_location (location_name) VALUES ('Kinarut');
INSERT INTO ospos_location (location_name) VALUES ('Kota Belud');
INSERT INTO ospos_location (location_name) VALUES ('Kota Kinabalu');
INSERT INTO ospos_location (location_name) VALUES ('Kudat');
INSERT INTO ospos_location (location_name) VALUES ('Lahad Datu');
INSERT INTO ospos_location (location_name) VALUES ('Papar');
INSERT INTO ospos_location (location_name) VALUES ('Putatan');
INSERT INTO ospos_location (location_name) VALUES ('Ranau');
INSERT INTO ospos_location (location_name) VALUES ('Sandakan');
INSERT INTO ospos_location (location_name) VALUES ('Semporna');
INSERT INTO ospos_location (location_name) VALUES ('Taman Rajawali');
INSERT INTO ospos_location (location_name) VALUES ('Tawau');
INSERT INTO ospos_location (location_name) VALUES ('Bintulu');
INSERT INTO ospos_location (location_name) VALUES ('Data Kakus');
INSERT INTO ospos_location (location_name) VALUES ('Kapit');
INSERT INTO ospos_location (location_name) VALUES ('Kuching');
INSERT INTO ospos_location (location_name) VALUES ('Lawas');
INSERT INTO ospos_location (location_name) VALUES ('Lidung Jelo');
INSERT INTO ospos_location (location_name) VALUES ('Limbang');
INSERT INTO ospos_location (location_name) VALUES ('Long Ampan Aing or Abanang');
INSERT INTO ospos_location (location_name) VALUES ('Marudi');
INSERT INTO ospos_location (location_name) VALUES ('Miri');
INSERT INTO ospos_location (location_name) VALUES ('Mukah');
INSERT INTO ospos_location (location_name) VALUES ('Sarikei');
INSERT INTO ospos_location (location_name) VALUES ('Sibu');
INSERT INTO ospos_location (location_name) VALUES ('Simanggang');
INSERT INTO ospos_location (location_name) VALUES ('Ampang');
INSERT INTO ospos_location (location_name) VALUES ('Bagan Pulau Ketam');
INSERT INTO ospos_location (location_name) VALUES ('Banting');
INSERT INTO ospos_location (location_name) VALUES ('Batang Berjuntai');
INSERT INTO ospos_location (location_name) VALUES ('Batu Arang');
INSERT INTO ospos_location (location_name) VALUES ('Jenjarum');
INSERT INTO ospos_location (location_name) VALUES ('Kampong Baharu Balakong');
INSERT INTO ospos_location (location_name) VALUES ('Kampung Baru Subang');
INSERT INTO ospos_location (location_name) VALUES ('Kampung Tanjung Karang');
INSERT INTO ospos_location (location_name) VALUES ('Klang');
INSERT INTO ospos_location (location_name) VALUES ('Kuala Selangor');
INSERT INTO ospos_location (location_name) VALUES ('Kuang');
INSERT INTO ospos_location (location_name) VALUES ('Ladang Seri Kundang');
INSERT INTO ospos_location (location_name) VALUES ('Pelabuhan Klang');
INSERT INTO ospos_location (location_name) VALUES ('Petaling Jaya');
INSERT INTO ospos_location (location_name) VALUES ('Putra Heights');
INSERT INTO ospos_location (location_name) VALUES ('Rawang');
INSERT INTO ospos_location (location_name) VALUES ('Semenyih');
INSERT INTO ospos_location (location_name) VALUES ('Serendah');
INSERT INTO ospos_location (location_name) VALUES ('Shah Alam');
INSERT INTO ospos_location (location_name) VALUES ('Subang Jaya');
INSERT INTO ospos_location (location_name) VALUES ('Sungai Besar');
INSERT INTO ospos_location (location_name) VALUES ('Sungai Pelek New Village');
INSERT INTO ospos_location (location_name) VALUES ('Tanjung Sepat');
INSERT INTO ospos_location (location_name) VALUES ('Cukai');
INSERT INTO ospos_location (location_name) VALUES ('Jertih');
INSERT INTO ospos_location (location_name) VALUES ('Kampung Kuala Besut');
INSERT INTO ospos_location (location_name) VALUES ('Kertih');
INSERT INTO ospos_location (location_name) VALUES ('Kuala Besut');
INSERT INTO ospos_location (location_name) VALUES ('Kuala Terengganu');
INSERT INTO ospos_location (location_name) VALUES ('Marang');
INSERT INTO ospos_location (location_name) VALUES ('Paka');
INSERT INTO ospos_location (location_name) VALUES ('Krubong');